//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Psswrd { get; set; }

        public static void CreateAdminProfile(Admin a)
        {
            throw new NotImplementedException();
        }
    }
}
